/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import trandpl.dao.QuestionDAO;
import trandpl.dao.ResultDAO;
import trandpl.pojo.CurrentUser;
import trandpl.pojo.QuestionPojo;
import trandpl.pojo.ResultPojo;

/**
 *
 * @author Sir2
 */
public class PtTakeQuizFrame extends javax.swing.JFrame {

    /**
     * Creates new form PtTakeQuizFrame
     */
   List<QuestionPojo>questionList;
    private String jobId,jobTitle;
    private QuestionPojo currentQuestion;
    int counter=0;
    List<Integer>userAnswerList;
   PtTakeQuizFrame pt=this;


    public PtTakeQuizFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public PtTakeQuizFrame(String jobId,String jobTitle) {


this();
this.jobId=jobId;
this.jobTitle=jobTitle;
lblTitle.setText("Paper For "+this.jobTitle);
lblQno.setText(""+(counter+1));        
this.setVisible(true);
loadQuestionPaper();       

    }
   private void loadQuestionPaper(){
        try{
questionList=QuestionDAO.getQuestionPaperByJobId(jobId);
userAnswerList=new ArrayList<Integer>(questionList.size());
System.out.println("Size of QL:"+questionList.size());
System.out.println("Size of Al:"+userAnswerList.size());
            for(int i=0;i<questionList.size();i++)
userAnswerList.add(i,0);
System.out.println("Size of Al:"+userAnswerList.size());
lblTitle.setText("Paper For "+this.jobTitle+" Total Questions:"+questionList.size());
showNextQuestionInFrame();
        }
        catch(SQLException ex){
JOptionPane.showMessageDialog(null,"DB Error In Quiz", "Error!!",JOptionPane.ERROR_MESSAGE);
ex.printStackTrace();
        }
    }
   
   private void showNextQuestionInFrame(){
currentQuestion=questionList.get(counter);
txtQuestion.setText(currentQuestion.getQuestion());
        jrbtn1.setText(currentQuestion.getOption1());
        jrbtn2.setText(currentQuestion.getOption2());
        jrbtn3.setText(currentQuestion.getOption3());
        jrbtn4.setText(currentQuestion.getOption4());
        int answer=userAnswerList.get(counter);
        switch(answer){
               case 1:
                        jrbtn1.setSelected(true);
                        break;
               case 2:
                        jrbtn2.setSelected(true);
                        break;
               case 3:
                        jrbtn3.setSelected(true);
                        break;
               case 4:
                        jrbtn4.setSelected(true);
                        break;
               default:
                        buttonGroup1.clearSelection();
           }   



    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbltime = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        Nextbtn = new javax.swing.JButton();
        btnDiscardPaper = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblQno = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jrbtn1 = new javax.swing.JRadioButton();
        jrbtn2 = new javax.swing.JRadioButton();
        jrbtn3 = new javax.swing.JRadioButton();
        jrbtn4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltime.setBackground(new java.awt.Color(243, 246, 254));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N

        btnSubmit.setBackground(new java.awt.Color(153, 204, 255));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnPrevious.setBackground(new java.awt.Color(153, 204, 255));
        btnPrevious.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        Nextbtn.setBackground(new java.awt.Color(153, 204, 255));
        Nextbtn.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        Nextbtn.setText("Next");
        Nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextbtnActionPerformed(evt);
            }
        });

        btnDiscardPaper.setBackground(new java.awt.Color(153, 204, 255));
        btnDiscardPaper.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        btnDiscardPaper.setText("Discard Paper");
        btnDiscardPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscardPaperActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Que.");

        txtQuestion.setBackground(new java.awt.Color(173, 192, 234));
        txtQuestion.setColumns(20);
        txtQuestion.setRows(5);
        jScrollPane1.setViewportView(txtQuestion);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Options -");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Option 1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Option 3");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Option 2");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Option 4");

        lblQno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblQno.setText("    ");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jrbtn1.setBackground(new java.awt.Color(173, 192, 234));
        buttonGroup1.add(jrbtn1);

        jrbtn2.setBackground(new java.awt.Color(173, 192, 234));
        buttonGroup1.add(jrbtn2);
        jrbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn2ActionPerformed(evt);
            }
        });

        jrbtn3.setBackground(new java.awt.Color(173, 192, 234));
        buttonGroup1.add(jrbtn3);
        jrbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn3ActionPerformed(evt);
            }
        });

        jrbtn4.setBackground(new java.awt.Color(173, 192, 234));
        buttonGroup1.add(jrbtn4);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Time  Left :");

        javax.swing.GroupLayout lbltimeLayout = new javax.swing.GroupLayout(lbltime);
        lbltime.setLayout(lbltimeLayout);
        lbltimeLayout.setHorizontalGroup(
            lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbltimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(lbltimeLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(Nextbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDiscardPaper)
                .addGap(58, 58, 58)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(lbltimeLayout.createSequentialGroup()
                .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lbltimeLayout.createSequentialGroup()
                .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbltimeLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(54, 54, 54)
                        .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jrbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(jrbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(125, 125, 125)
                        .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jrbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(jrbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(lbltimeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(lblQno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lbltimeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lbltimeLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        lbltimeLayout.setVerticalGroup(
            lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbltimeLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lbltimeLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lbltimeLayout.createSequentialGroup()
                                .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 34, Short.MAX_VALUE)
                                .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jrbtn1)))
                            .addGroup(lbltimeLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jrbtn2)))
                        .addGap(51, 51, 51)
                        .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbtn4)
                            .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jrbtn3)))
                        .addGap(148, 148, 148)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPrevious)
                                .addComponent(Nextbtn)
                                .addComponent(jLabel4))
                            .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDiscardPaper)
                                .addComponent(btnSubmit)))
                        .addGap(30, 30, 30))
                    .addGroup(lbltimeLayout.createSequentialGroup()
                        .addGroup(lbltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQno))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbltime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbltime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtn3ActionPerformed

    private void jrbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtn2ActionPerformed

    private void btnDiscardPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscardPaperActionPerformed
        // TODO add your handling code here:
        new PtViewAllAppliedJobsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDiscardPaperActionPerformed

    private void NextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextbtnActionPerformed
       
int res=validateChooseOption();
        if(res==0){
JOptionPane.showMessageDialog(null,"Please Select An Option","No Option Selected!",JOptionPane.WARNING_MESSAGE);
            return;
        }
userAnswerList.set(counter, res);
        ++counter;
        if(counter==questionList.size()){
            counter=0;
        }
showNextQuestionInFrame();
lblQno.setText(""+(counter+1));

    }//GEN-LAST:event_NextbtnActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
         int res=validateChooseOption();
        if(res==0){
JOptionPane.showMessageDialog(null,"Please Select An Option","No Option Selected!",JOptionPane.WARNING_MESSAGE);
            return;
        }
userAnswerList.set(counter, res);
        --counter;
        if(counter==-1){
            counter=questionList.size()-1;
        }
showNextQuestionInFrame();
lblQno.setText(""+(counter+1));
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        int res=validateChooseOption();
        if(res==0){
JOptionPane.showMessageDialog(null,"Please Select An Option","No Option Selected!",JOptionPane.WARNING_MESSAGE);
            return;
        }
userAnswerList.set(counter, res);
        double per=getPercentage();
ResultPojo result=new ResultPojo();
result.setJobId(jobId);
result.setpId(CurrentUser.getId());
        if(per<5)
            per=5.0;
result.setPercentage(per);
result.setSelectedByHr("No");
        try{
boolean resp=ResultDAO.setResult(result);
            if(resp==true){
JOptionPane.showMessageDialog(null,"You Got "+per+"% marks+\nAnd Result Has Been Sent On Your Mail","Result!",JOptionPane.INFORMATION_MESSAGE);
                new PtViewAllAppliedJobsFrame().setVisible(true);
this.dispose();
            }

        }
        catch(SQLException ex){
JOptionPane.showMessageDialog(null,"DB Error In Taake Test", "Error!!",JOptionPane.ERROR_MESSAGE);
ex.printStackTrace();
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PtTakeQuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PtTakeQuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PtTakeQuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PtTakeQuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PtTakeQuizFrame().setVisible(true);
            }
        });
    }
    private int validateChooseOption() 
    {
        if(jrbtn1.isSelected())
            return 1;
        else if(jrbtn2.isSelected())
            return 2;
        else if(jrbtn3.isSelected())
            return 3;
        else if(jrbtn4.isSelected())
            return 4;   
        else
            return 0;
    }



private double getPercentage(){
        int marksObtained=0;
        for(int i=0;i<questionList.size();i++){
QuestionPojo question=questionList.get(i);
            if(question.getCorrectOption()==userAnswerList.get(i)){
                ++marksObtained;
            }
        }
        double per=((double)marksObtained/questionList.size())*100;
        return per;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Nextbtn;
    private javax.swing.JButton btnDiscardPaper;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JRadioButton jrbtn1;
    private javax.swing.JRadioButton jrbtn2;
    private javax.swing.JRadioButton jrbtn3;
    private javax.swing.JRadioButton jrbtn4;
    private javax.swing.JLabel lblQno;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel lbltime;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables
}
